<a href="https://colab.research.google.com/github/tusharpoddar/e-Science-Research/blob/master/GoogleDrive/tf_record_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The following notebook is used to generate the tf-records from the VGGish model. 
In order to plot the cluster plot it is important to extract the tf-records(they provide us with the location of the spectrogram). This file shows how to generate the tf-records for a numpy file that has been generated before.

## What is the use of the tf-records?
The tf-records generated can be used to plot the cluster plot. The tf records help in specifying the relative position of the spectrograms with others. Similar spectrograms are plotted together and the ones that are different are plotted farther away. 

The notebooks does the following - 
1. Asks the user to specify the numpy file that contains all the data that needs to fed to the VGGis model(needs to be in (?, 96, 64)). 
2. Stores the tf-records in the file specified by the user. 

Note - The following notebook needs GPU for the generation of the records. It does not work on a normal jupyter local host on a mac book pro. 




In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
!pip install numpy resampy tensorflow==1.15 tf_slim six soundfile

     |████████████████████████████████| 412.3MB 25kB/s 
     |████████████████████████████████| 358kB 36.1MB/s 
     |████████████████████████████████| 51kB 4.9MB/s 
     |████████████████████████████████| 3.8MB 41.0MB/s 
     |████████████████████████████████| 512kB 47.5MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=59c159a3f2e84da0ec399f32862a183e74ce8237f9a3314c3f5e16a206d35d74
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorf

In [3]:
pip install netcdf4

     |████████████████████████████████| 4.3MB 3.5MB/s 
     |████████████████████████████████| 296kB 44.2MB/s 


In [4]:
# to open the selection tables
import pandas as pd

In [ ]:
cd gdrive/Shared\ drives/Research

/content/gdrive/Shared drives/Research


In [ ]:
%run vggish_inference_demo.py

Instructions for updating:
non-resource variables are not supported in the long term


(1759, 96, 64)


W0715 08:07:54.174680 140310280320896 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0715 08:07:54.269282 140310280320896 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tf_slim/layers/layers.py:1666: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
I0715 08:07:54.466761 140310280320896 saver.py:1284] Restoring parameters from vggish_model.ckpt


[[ 0.         0.         2.1669078 ...  0.         0.         0.       ]
 [ 0.         0.         4.808841  ...  0.         0.         0.       ]
 [ 0.         0.        74.74665   ...  0.         0.         0.       ]
 ...
 [ 0.         0.         5.9229727 ...  0.         0.         0.       ]
 [ 0.         0.         4.248594  ...  0.         0.         0.       ]
 [ 0.         0.         1.3496886 ...  0.         0.         0.       ]]
[[196   0 228 ...   0  76 180]
 [211   0 253 ...   0   0   0]
 [255   0 255 ... 255   0   0]
 ...
 [215   0 251 ... 255   0   0]
 [187   0 229 ...   0   0  53]
 [186   0 202 ...   0   0 255]]
feature_lists {
  feature_list {
    key: "audio_embedding"
    value {
      feature {
        bytes_list {
          value: "\304\000\344+\263Cp\000\360\377\233Z\000\377\226\rT\377\013\375\377\000\000}\377{\000\377\000\377\254\377\377M\000\000\377\377\356\377\000\331\000q\377\000\260\000\257k\306\000\000\000\377\377\000\000\377\001\377\000\0005\341\000\377\377

In [ ]:
import make_spectrogram

In [ ]:
path = '/content/gdrive/Shared drives/Research/Data/Wav Files/2min6sec.wav'

In [ ]:
gitArr = make_spectrogram.spectrogram_generate(path)

Length: 126.843612 sec
Audio shape: (31710903,), Sliced audio shape: (5637, 6250)
(310035, 257)
(5637, 55, 257)


In [ ]:
numpyArray = np.array(gitArr)

In [ ]:
numpyArray.shape

(5637, 96, 64)

In [ ]:
np.save('git2min6sec-spectrogram', numpyArray)