In [10]:
from vggish_input import waveform_to_examples, wavfile_to_examples

In [49]:
import mel_features
import vggish_params
import numpy as np

In [50]:
from scipy.io import wavfile
# code if i wrote the first code
fs, data = wavfile.read('tester.wav')

In [51]:
out = wavfile_to_examples('tester.wav')

In [52]:
out.shape

(60, 96, 64)

In [64]:
out2 = spectrogram_to_mel_matrix()

out2

In [66]:
# this is the output of the function spectogram_to_mel_matrix 
# this returns the things that when multiplyed to the spectrogram rows returns the mel frequencies. 
out2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [55]:
out2.shape

(129, 20)

In [56]:
log_mel = mel_features.log_mel_spectrogram(
      data,
      audio_sample_rate=vggish_params.SAMPLE_RATE,
      log_offset=vggish_params.LOG_OFFSET,
      window_length_secs=vggish_params.STFT_WINDOW_LENGTH_SECONDS,
      hop_length_secs=vggish_params.STFT_HOP_LENGTH_SECONDS,
      num_mel_bins=vggish_params.NUM_MEL_BINS,
      lower_edge_hertz=vggish_params.MEL_MIN_HZ,
      upper_edge_hertz=vggish_params.MEL_MAX_HZ)

In [57]:
# Convert waveform to a log magnitude mel-frequency spectrogram.
# it is the output of the function log_mel_spectrogram with all the default values set in the 
# vggish_params
log_mel

array([[-0.27557773, -1.76160742, -0.73949844, ...,  5.67429201,
         5.69911036,  5.72045365],
       [-1.6658181 , -0.26183987,  0.07214821, ...,  6.05859627,
         5.58864523,  6.15681301],
       [-0.57573858, -0.22186723, -0.44570719, ...,  5.4817578 ,
         5.5764798 ,  5.92166707],
       ...,
       [ 5.4403983 ,  6.70652481,  6.75729466, ..., 10.28657083,
        10.55407061, 10.26884819],
       [ 7.35942218,  6.79766863,  7.02358122, ..., 10.21173596,
        10.62168468, 10.48802175],
       [ 7.81289068,  7.71500035,  7.62591333, ..., 10.76397119,
        10.66253467, 10.86635603]])

In [58]:
log_mel.shape

(91242, 64)

In [59]:
audio_sample_rate = vggish_params.SAMPLE_RATE
log_offset = vggish_params.LOG_OFFSET
window_length_secs = vggish_params.STFT_WINDOW_LENGTH_SECONDS
hop_length_secs = vggish_params.STFT_HOP_LENGTH_SECONDS
num_mel_bins = vggish_params.NUM_MEL_BINS
lower_edge_hertz = vggish_params.MEL_MIN_HZ
upper_edge_hertz = vggish_params.MEL_MAX_HZ

In [61]:
window_length_samples = int(round(audio_sample_rate * window_length_secs))
hop_length_samples = int(round(audio_sample_rate * hop_length_secs))
fft_length = 2 ** int(np.ceil(np.log(window_length_samples) / np.log(2.0)))
spectrogram = mel_features.stft_magnitude(
  data,
  fft_length=fft_length,
  hop_length=hop_length_samples,
  window_length=window_length_samples)

In [71]:
spectrogram

array([[8.60813416e-01, 5.42563873e-01, 1.58312082e-01, ...,
        5.72768742e+01, 1.10017659e+02, 1.56208602e+02],
       [2.17604711e-01, 5.03624093e-01, 6.54539601e-01, ...,
        7.44196857e+01, 6.72284240e+01, 8.67289063e+01],
       [1.75819256e+00, 1.44518033e+00, 6.43957530e-01, ...,
        1.06189710e+02, 9.35090550e+01, 8.83931108e+01],
       ...,
       [2.12209092e+03, 1.54657527e+03, 7.47913958e+02, ...,
        1.41248567e+03, 9.99595683e+02, 7.53036701e+02],
       [2.02666709e+03, 1.50241378e+03, 1.53997994e+03, ...,
        1.21658183e+03, 1.17161810e+03, 2.46944520e+02],
       [1.91660953e+03, 6.41451760e+02, 1.39245630e+03, ...,
        6.61934027e+02, 1.37606691e+03, 1.71006532e+03]])

In [69]:
out3 = mel_features.spectrogram_to_mel_matrix(
  num_spectrogram_bins=spectrogram.shape[1],
  audio_sample_rate=audio_sample_rate)

In [70]:
out3

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
mel_spectrogram = np.dot(spectrogram, mel_features.spectrogram_to_mel_matrix(
  num_spectrogram_bins=spectrogram.shape[1],
  audio_sample_rate=audio_sample_rate))
out4 = np.log(mel_spectrogram + log_offset)

In [74]:
# this is the putput of the function log_mel_spectrogram which gives me the final 
# this function basically gives me the frequency sets for the 20 bins or windows specified to it. 
out4

array([[ 0.04036001,  1.28598483,  1.27634565, ...,  3.6582319 ,
         4.30877001,  4.10539642],
       [ 0.59529856,  0.89597388,  0.51989108, ...,  3.53544929,
         3.93804777,  4.29369399],
       [ 0.39974866,  0.42423455,  0.85056843, ...,  3.52841536,
         3.63124529,  4.21481369],
       ...,
       [ 7.55867075,  8.25282515,  9.05141303, ..., 10.9386666 ,
        11.23663871, 10.93751383],
       [ 7.94853074,  8.54028604,  9.16722208, ..., 10.82000508,
        10.73294982, 10.85359564],
       [ 8.49011784,  7.78180419,  9.13201074, ..., 10.75516349,
        10.92866097, 10.75284771]])

In [75]:
out4.shape

(91242, 20)

In [76]:
# so this function basically converts given set of frequecis to the mel ones according to the HKV 
# fourmula 
out5 = mel_features.hertz_to_mel(fs)

In [77]:
out5

6627.8103066390595

In [78]:
# so basically it is difficlt to find the frequencies that are used to plot the mel 
# so a better thing to do in this case is to find the evely spaced things in the max and the min of the frequencies
# and then converting it to the mel frequencies 

final_freqs = np.linspace(0,125001,64)
final_frequencies = mel_features.hertz_to_mel(final_freqs)


In [79]:
final_frequencies

array([   0.        , 1514.72900826, 2138.44515516, 2537.61736084,
       2831.79106167, 3064.85533047, 3257.88333188, 3422.63449506,
       3566.34464939, 3693.78466869, 3808.26677121, 3912.18453245,
       4007.32403388, 4095.05350033, 4176.44426732, 4252.35091293,
       4323.46605541, 4390.35885877, 4453.50273441, 4513.29568377,
       4570.07551017, 4624.13137832, 4675.71272593, 4725.03622334,
       4772.29127286, 4817.64440076, 4861.24279904, 4903.21720735,
       4943.68427704, 4982.74852542, 5020.50396236, 5057.03545323,
       5092.41986774, 5126.72705388, 5160.02066787, 5192.35888507,
       5223.79501168, 5254.37801339, 5284.15297421, 5313.16149621,
       5341.44204909, 5369.03027696, 5395.95926849, 5422.25979544,
       5447.96052408, 5473.08820302, 5497.66783048, 5521.7228038 ,
       5545.27505326, 5568.34516222, 5590.95247525, 5613.11519553,
       5634.85047296, 5656.17448385, 5677.10250327, 5697.64897078,
       5717.82755027, 5737.65118452, 5757.13214511, 5776.28207

In [80]:
final_freqs

array([     0.        ,   1984.14285714,   3968.28571429,   5952.42857143,
         7936.57142857,   9920.71428571,  11904.85714286,  13889.        ,
        15873.14285714,  17857.28571429,  19841.42857143,  21825.57142857,
        23809.71428571,  25793.85714286,  27778.        ,  29762.14285714,
        31746.28571429,  33730.42857143,  35714.57142857,  37698.71428571,
        39682.85714286,  41667.        ,  43651.14285714,  45635.28571429,
        47619.42857143,  49603.57142857,  51587.71428571,  53571.85714286,
        55556.        ,  57540.14285714,  59524.28571429,  61508.42857143,
        63492.57142857,  65476.71428571,  67460.85714286,  69445.        ,
        71429.14285714,  73413.28571429,  75397.42857143,  77381.57142857,
        79365.71428571,  81349.85714286,  83334.        ,  85318.14285714,
        87302.28571429,  89286.42857143,  91270.57142857,  93254.71428571,
        95238.85714286,  97223.        ,  99207.14285714, 101191.28571429,
       103175.42857143, 1